# Generated by Django 4.2 on 2025-11-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SESEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('bounce', 'Bounce'), ('complaint', 'Complaint'), ('delivery', 'Delivery')], db_index=True, max_length=20)),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('bounce_type', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Transient', 'Transient'), ('Undetermined', 'Undetermined')], max_length=20, null=True)),
                ('bounce_sub_type', models.CharField(blank=True, max_length=50, null=True)),
                ('complaint_feedback_type', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('raw_message', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SES Event',
                'verbose_name_plural': 'SES Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
