# Generated by Django 4.2 on 2025-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesevent',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sesevent',
            name='event_type',
            field=models.CharField(choices=[('bounce', 'Bounce'), ('complaint', 'Complaint'), ('delivery', 'Delivery'), ('send', 'Send'), ('reject', 'Reject'), ('rendering_failure', 'Rendering Failure'), ('delivery_delay', 'Delivery Delay'), ('subscription', 'Subscription')], db_index=True, max_length=20),
        ),
    ]
