# Generated by Django 4.2 on 2025-12-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses_tracking', '0002_sesevent_reject_reason_alter_sesevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmailStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_sends', models.IntegerField(default=0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_bounces', models.IntegerField(default=0)),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_rejects', models.IntegerField(default=0)),
                ('total_rendering_failures', models.IntegerField(default=0)),
                ('total_delivery_delays', models.IntegerField(default=0)),
                ('total_subscriptions', models.IntegerField(default=0)),
                ('permanent_bounces', models.IntegerField(default=0)),
                ('transient_bounces', models.IntegerField(default=0)),
                ('undetermined_bounces', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('complaint_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unique_recipients', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Email Statistics',
                'verbose_name_plural': 'Daily Email Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='sesevent',
            name='email_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='dailyemailstats',
            index=models.Index(fields=['-date'], name='ses_trackin_date_1e6986_idx'),
        ),
    ]
