# Generated by Django 4.2 on 2025-11-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ses_tracking', '0003_dailyemailstats_sesevent_email_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesevent',
            name='email_subject',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sesevent',
            name='email_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
